#pragma once

#include "physics/rigid_body.h"

#include <stdbool.h>
#include <stdint.h>

#define VOXEL_RAGDOLL_MAX_BODIES 16u
#define VOXEL_RAGDOLL_MAX_JOINTS (VOXEL_RAGDOLL_MAX_BODIES - 1u)
#define VOXEL_RAGDOLL_DEFAULT_JOINT_ITERATIONS 8u

typedef struct VoxelRagdollBodyDefinition
{
    // Center relative to the ragdoll origin; the part begins axis-aligned.
    double offset[3];
    double halfExtent[3];
    double mass;
    double restitution;
    double friction;
} VoxelRagdollBodyDefinition;

typedef struct VoxelRagdollBallJointDefinition
{
    uint32_t bodyA;
    uint32_t bodyB;
    // The two anchors are in the local coordinates of their respective boxes.
    double anchorA[3];
    double anchorB[3];
} VoxelRagdollBallJointDefinition;

typedef struct VoxelRagdollDefinition
{
    uint64_t stableIdBase;
    double origin[3];
    const VoxelRagdollBodyDefinition *bodies;
    uint32_t bodyCount;
    const VoxelRagdollBallJointDefinition *joints;
    uint32_t jointCount;
    uint32_t rootBody;
} VoxelRagdollDefinition;

typedef struct VoxelRagdollSettings
{
    uint32_t solverIterations;
    // Fraction of anchor error corrected per 1/128-second step, in [0, 0.5].
    double errorCorrection;
    // Clamp for the velocity bias generated by a separated joint anchor.
    double maximumCorrectionSpeed;
} VoxelRagdollSettings;

typedef struct VoxelRagdoll
{
    VoxelRigidBody bodies[VOXEL_RAGDOLL_MAX_BODIES];
    VoxelRagdollBallJointDefinition joints[VOXEL_RAGDOLL_MAX_JOINTS];
    uint32_t bodyCount;
    uint32_t jointCount;
    uint32_t rootBody;
    bool initialized;
} VoxelRagdoll;

LAIUE_PHYSICS_API void VoxelRagdollSettingsDefault(VoxelRagdollSettings *outSettings);
// A ragdoll is a connected tree of at most 16 axis-aligned starting boxes.
// Joint anchors must lie in each box and coincide in the initial pose. The
// object must be zero-initialized or released before initialization. Failed
// initialization releases every body it created and leaves the object zeroed.
LAIUE_PHYSICS_API bool VoxelRagdollInitialize(VoxelRagdoll *ragdoll,
                                             const VoxelRagdollDefinition *definition);
LAIUE_PHYSICS_API void VoxelRagdollRelease(VoxelRagdoll *ragdoll);
// Runs the ordinary rigid-body/contact step and then the fixed-order ball
// joints. options may be NULL to use canonical rigid-body ordering. As with
// VoxelRigidBodyStepEx, a late failure can leave a partial tick.
LAIUE_PHYSICS_API bool VoxelRagdollStep(
    VoxelRagdoll *ragdoll, const VoxelCollisionSource *collision,
    const VoxelRigidStepSettings *rigidSettings, const VoxelRagdollSettings *settings,
    void *scratch, uint32_t scratchBytes, const VoxelRigidStepOptions *options);
// Camera/world-relative planar direction must have length <= 1. Motion is a
// bounded velocity motor on the root body; all limbs remain dynamically solved.
LAIUE_PHYSICS_API bool VoxelRagdollDrive(VoxelRagdoll *ragdoll, double directionX,
                                        double directionY, double targetSpeed,
                                        double maximumAcceleration);
// Adds the same vertical velocity to all parts, preserving their relative
// motion. The game decides when a jump is allowed.
LAIUE_PHYSICS_API bool VoxelRagdollJump(VoxelRagdoll *ragdoll, double upwardSpeed);
