#include "core/application_config.h"

const ApplicationConfiguration g_applicationConfiguration = {
    .windowTitle = L"laiue",
    .windowWidth = 640,
    .windowHeight = 360,
    .cameraSpeed = 80.0f,
    .mouseSensitivity = 0.0025f,
    .fieldOfViewRadians = 1.047197f,
    .nearPlane = 0.1f,
    .farPlane = 1000.0f,
    .editReachDistance = 8.0f,
    .viewRadiusChunks = 5,
    .worldSeed = 42,
    .rebaseThresholdBlocks = 1048576,
    .spawnHeight = 100.0,
    .player = {
        .walkingSpeed = 7.0f,
        .crouchingSpeed = 3.5f,
        .gravity = 26.0f,
        .maximumFallSpeed = 55.0f,
        .jumpBufferSeconds = 0.14f,
        .coyoteTimeSeconds = 0.10f,
        .externalVelocityDamping = 8.0f,
        .fixedStepSeconds = 1.0f / 240.0f,
        .maximumSubsteps = 32u,
        .jumpHeight = 1.275,
        .radius = 0.30,
        .standingHeight = 1.80,
        .standingEyeHeight = 1.75,
        .crouchingHeight = 1.30,
        .crouchingEyeHeight = 1.25,
        .collisionEpsilon = 0.001,
        .groundProbeDepth = 0.03,
        .ledgeSupportRadius = 0.05,
    },
};
