if(NOT DEFINED SOURCE_ROOT)
    get_filename_component(SOURCE_ROOT
        "${CMAKE_CURRENT_LIST_DIR}/../src" ABSOLUTE)
endif()

set(allowed_audio audio)
set(allowed_content content platform)
set(allowed_core
    audio content core game gameplay input interaction mesh mod network
    physics platform render world)
set(allowed_game game)
set(allowed_gameplay game gameplay physics)
set(allowed_input input)
set(allowed_interaction interaction physics world)
set(allowed_launcher launcher)
set(allowed_mesh mesh render world)
set(allowed_mod content game gameplay mod platform world)
set(allowed_network network platform)
set(allowed_physics physics)
set(allowed_platform platform)
set(allowed_render content render)
set(allowed_runtime runtime)
set(allowed_server
    content game gameplay interaction mod network physics platform server world)
set(allowed_world platform world)

file(GLOB_RECURSE source_files
    "${SOURCE_ROOT}/*.c" "${SOURCE_ROOT}/*.h")
set(violations)
set(checked 0)
foreach(source_file IN LISTS source_files)
    file(RELATIVE_PATH relative "${SOURCE_ROOT}" "${source_file}")
    string(REPLACE "\\" "/" relative "${relative}")
    if(relative MATCHES "(^|/)generated/")
        continue()
    endif()
    if(NOT relative MATCHES "^([^/]+)/")
        continue()
    endif()
    set(owner "${CMAKE_MATCH_1}")
    if(NOT DEFINED allowed_${owner})
        list(APPEND violations
            "${relative}: unknown module '${owner}'")
        continue()
    endif()
    math(EXPR checked "${checked} + 1")
    file(STRINGS "${source_file}" lines)
    set(line_number 0)
    foreach(line IN LISTS lines)
        math(EXPR line_number "${line_number} + 1")
        if(NOT line MATCHES "^[ \t]*#[ \t]*include[ \t]*\"([^\"]+)\"")
            continue()
        endif()
        set(include "${CMAKE_MATCH_1}")
        string(REPLACE "\\" "/" include "${include}")
        if(include MATCHES "(^|/)\\.\\.(/|$)")
            list(APPEND violations
                "${relative}:${line_number}: relative include '${include}' is forbidden")
            continue()
        endif()
        if(NOT include MATCHES "^([^/]+)/")
            continue()
        endif()
        set(dependency "${CMAKE_MATCH_1}")
        list(FIND allowed_${owner} "${dependency}" allowed_index)
        if(allowed_index EQUAL -1)
            list(APPEND violations
                "${relative}:${line_number}: module '${owner}' cannot include '${include}'")
        endif()
    endforeach()
endforeach()

if(violations)
    list(JOIN violations "\n  " formatted)
    message(FATAL_ERROR "Architecture boundary violations:\n  ${formatted}")
endif()
message(STATUS "Architecture boundaries: OK (${checked} files)")
