if(NOT DEFINED INPUT_FILE OR "${INPUT_FILE}" STREQUAL "")
    message(FATAL_ERROR "INPUT_FILE is required")
endif()

file(READ "${INPUT_FILE}" contents)
string(REPLACE "\r\n" "\n" contents "${contents}")
string(REPLACE "\r" "\n" contents "${contents}")
string(REGEX REPLACE " +\n" "\n" contents "${contents}")
string(REGEX REPLACE "\n+$" "\n" contents "${contents}")
file(WRITE "${INPUT_FILE}" "${contents}")
