#pragma once

#include "api.h"

#include <stdint.h>

#define LAIUE_MOD_DIAGNOSTIC_CAPACITY 256u
#define LAIUE_MOD_SERVICE_NAME_CAPACITY 96u

typedef enum LaiueModStatus
{
    LAIUE_MOD_STATUS_OK = 0,
    LAIUE_MOD_STATUS_INVALID_ARGUMENT,
    LAIUE_MOD_STATUS_OUT_OF_MEMORY,
    LAIUE_MOD_STATUS_BUSY,
    LAIUE_MOD_STATUS_CAPACITY_EXCEEDED,
    LAIUE_MOD_STATUS_UNSAFE_PACK_NAME,
    LAIUE_MOD_STATUS_PACK_NOT_FOUND,
    LAIUE_MOD_STATUS_PACK_NOT_DIRECTORY,
    LAIUE_MOD_STATUS_PACK_IS_SYMBOLIC_LINK,
    LAIUE_MOD_STATUS_MANIFEST_NOT_FOUND,
    LAIUE_MOD_STATUS_MANIFEST_TOO_LARGE,
    LAIUE_MOD_STATUS_MANIFEST_INVALID,
    LAIUE_MOD_STATUS_ENGINE_INCOMPATIBLE,
    LAIUE_MOD_STATUS_ABI_INCOMPATIBLE,
    LAIUE_MOD_STATUS_PLATFORM_UNSUPPORTED,
    LAIUE_MOD_STATUS_NATIVE_ARTIFACT_INVALID,
    LAIUE_MOD_STATUS_NATIVE_ARTIFACT_NOT_FOUND,
    LAIUE_MOD_STATUS_NATIVE_ARTIFACT_IS_SYMBOLIC_LINK,
    LAIUE_MOD_STATUS_LIBRARY_LOAD_FAILED,
    LAIUE_MOD_STATUS_ENTRY_POINT_MISSING,
    LAIUE_MOD_STATUS_INITIALIZATION_FAILED,
    LAIUE_MOD_STATUS_EXPORTS_INVALID,
    LAIUE_MOD_STATUS_ALREADY_LOADED,
    LAIUE_MOD_STATUS_NOT_LOADED,
    LAIUE_MOD_STATUS_SERVICE_NAME_INVALID,
    LAIUE_MOD_STATUS_SERVICE_ALREADY_REGISTERED,
    LAIUE_MOD_STATUS_SERVICE_NOT_FOUND,
    LAIUE_MOD_STATUS_PACK_NAME_COLLISION,
} LaiueModStatus;

typedef struct LaiueModDiagnostic
{
    LaiueModStatus status;
    int32_t modResult;
    char message[LAIUE_MOD_DIAGNOSTIC_CAPACITY];
} LaiueModDiagnostic;

LAIUE_MOD_API const char *LaiueModStatusString(LaiueModStatus status);
